[versions]
version = "2"
app-version = "1.0.1"

androidx-navigation = "2.9.0-beta03"
androidx-lifecycle = "2.9.1"
compose-multiplatform = "1.8.2"
junit = "4.13.2"
kotlin = "2.1.21"
ksp = "2.1.21-2.0.1"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
materialKolor = "2.1.1"
composeIcons = "1.1.1"
androidx-paging = "3.3.6"
paging-compose = "3.3.0-alpha02-0.5.1"
androidx-room = "2.7.2"
sqlite-bundled = "2.5.2"
koin = "4.1.0"
km-logging = "2.0.3"
slf4j = "2.0.17"
coil = "3.2.0"
ktor = "3.2.2"
filekit = "0.10.0-beta04"
buildKonfig = "0.17.1"
kmp-process = "0.3.1"
compose-settings = "2.13.0"
androidx-datastore = "1.1.7"
appDir = "2.0.0"
aboutLibraries = "12.2.4"
autoLaunch = "0.6.0"
detekt = "1.23.8"

[libraries]

# navigation
androidx-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }

# lifecycle
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

# coroutine
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

# material-kolor
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }

# icons
composeIcons-tablerIcons = { module = "br.com.devsrsouza.compose.icons:tabler-icons", version.ref = "composeIcons" }

# serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# paging
androidx-paging-runtime = { group = "androidx.paging", name = "paging-common", version.ref = "androidx-paging" }
cashapp-paging-compose = { group = "app.cash.paging", name = "paging-compose-common", version.ref = "paging-compose" }

# coil
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

# file
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }

# ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }

# Room
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "androidx-room" }
androidx-sqlite-bundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite-bundled" }
androidx-sqlite-bundled-jvm = { group = "androidx.sqlite", name = "sqlite-bundled-jvm", version.ref = "sqlite-bundled" }

# koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose-core = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-compose-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation", version.ref = "koin" }

# kotlin-logging
km-logging = { module = "com.diamondedge:logging", version.ref = "km-logging" }

# kmp-process
kmp-process = { module = "io.matthewnelson.kmp-process:process", version.ref = "kmp-process" }

# settings
composeSettings-ui = { group = "com.github.alorma.compose-settings", name = "ui-tiles", version.ref = "compose-settings" }
composeSettings-ui-extended = { group = "com.github.alorma.compose-settings", name = "ui-tiles-extended", version.ref = "compose-settings" }

# dataStore
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }

# appDir
appDirs = { module = "ca.gosyer:kotlin-multiplatform-appdirs", version.ref = "appDir" }

# aboutLibraries
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }

# autoLaunch
autoLaunch = { module = "io.github.vinceglb:auto-launch", version.ref = "autoLaunch" }

# test
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

# builcKonfig
buildKonfig = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "buildKonfig" }

# detekt
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

[plugins]
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "androidx-room" }
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }


[bundles]
coroutines = ["kotlinx-coroutines-core", "kotlinx-coroutines-swing"]
room = ["androidx-room-runtime", "androidx-room-paging", "androidx-sqlite-bundled", "androidx-sqlite-bundled-jvm"]
koin = ["koin-core", "koin-compose-core", "koin-compose-viewmodel", "koin-compose-navigation"]
paging = ["androidx-paging-runtime", "cashapp-paging-compose"]
coil = ["coil-compose", "coil-ktor"]
filekit = ["filekit-dialogs", "filekit-dialogs-compose"]
settings = ["composeSettings-ui", "composeSettings-ui-extended"]